query getLayout {
    menus {
        nodes {
            id
            slug

            menuItems {
                edges {
                    node {
                        id
                        uri
                        label
                        parentId
                        target
                    }
                }
            }
        }
    }
    seo {
        schema {
            siteName
            siteUrl
        }
    }
    settingsAll {
        gQLSettings {
            headerRemove {
                email {
                    title
                    url
                    target
                }
                link {
                    title
                    url
                    target
                }
                logoMobile {
                    node {
                        sourceUrl
                    }
                }
                logoBtn {
                    url
                    logo {
                        node {
                            sourceUrl
                        }
                    }
                }
                social {
                    link {
                        url
                        title
                        target
                    }
                    icon
                }
                tel {
                    url
                    title
                    target
                }
            }
            footer {
                address {
                    link {
                        title
                        url
                        target
                    }
                    addressLocality
                    streetAddress
                    postalCode
                    addressCountry
                }
                email {
                    title
                    url
                    target
                }
                logoBtn {
                    url
                    logo {
                        node {
                            sourceUrl
                        }
                    }
                }
                tel {
                    title
                    url
                    target
                }
                social {
                    link {
                        url
                        title
                        target
                    }
                    icon
                }
                linkCopy {
                    title
                    url
                    target
                }
                link {
                    url
                    title
                    target
                }
            }
            formModalCommon {
                id
                hash
                title
                descr
                nameBtn
                successMessage
                cf7FormDynamicFields
                yandexMetrikaList {
                    name
                }
            }
        }
    }
}
