query getPosts($offset: Int!, $size: Int!) {
    posts(where: { offsetPagination: { offset: $offset, size: $size } }) {
        edges {
            node {
                title
                date
                uri
                postViews
                featuredImage {
                    node {
                        sourceUrl
                    }
                }
                contentPost {
                    contentPost {
                        authorPost
                        listLevel1 {
                            link {
                                url
                                title
                                target
                            }
                            listLevel2 {
                                link {
                                    url
                                    title
                                    target
                                }
                            }
                        }
                    }
                }
                comments {
                    edges {
                        node {
                            id
                            content
                            author {
                                email
                                name
                            }
                        }
                    }
                }
                seo {
                    title
                    metaDesc
                    canonical
                    breadcrumbs {
                        url
                        text
                    }
                    metaRobotsNoindex
                    metaRobotsNofollow
                    metaKeywords
                }
            }
        }
        totalPosts
    }
}
