query NewQuery {
    settingsAll {
        gQLSettings {
            aboutCommon {
                title
                aboutList {
                    descr
                    title
                }
            }
            advantagesCommon {
                advantagesList {
                    title
                    subtitle
                    icon {
                        node {
                            webpSrcSet
                            webpSourceUrl
                            sourceUrl
                            title
                        }
                    }
                }
                title
            }
            casesCommon {
                title
                casesCommonList {
                    descr
                    elems {
                        descr
                        title
                    }
                    title
                }
            }
            clientsCommon {
                list {
                    img {
                        node {
                            sourceUrl
                            webpSrcSet
                            webpSourceUrl
                        }
                    }
                }
                title
            }
            commandCommon {
                descr
                list {
                    descr
                    title
                    position
                    img {
                        node {
                            sourceUrl
                            webpSrcSet
                            webpSourceUrl
                        }
                    }
                }
                title
            }
            corpServiesCommon {
                corpServiesList {
                    nodes {
                        ... on PostService {
                            id
                            uri
                            title
                            featuredImage {
                                node {
                                    sourceUrl
                                    webpSrcSet
                                    webpSourceUrl
                                }
                            }
                            pageBuilder {
                                flexible {
                                    ... on PageBuilderFlexibleHeroCustomLayout {
                                        heroCustom {
                                            subtitle
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            costServiesCommon {
                btn {
                    title
                    url
                }
                reverse
                descr
                img1 {
                    node {
                        sourceUrl
                        webpSrcSet
                        webpSourceUrl
                    }
                }
                img2 {
                    node {
                        sourceUrl
                        webpSrcSet
                        webpSourceUrl
                    }
                }
                title
            }
            ctaCommon {
                title
                descr
                btn {
                    title
                    url
                }
                bg {
                    node {
                        sourceUrl
                        webpSrcSet
                        webpSourceUrl
                    }
                }
                yandexMetrikaList {
                    name
                }
            }
            cta2Common {
                img {
                    node {
                        sourceUrl
                        webpSrcSet
                        webpSourceUrl
                    }
                }
                title
                subtitle
                descr
                btn {
                    url
                    title
                }
                yandexMetrikaList {
                    name
                }
            }
            ctaTelegramCommon {
                descr
                btn {
                    url
                    title
                }
                title
                img {
                    node {
                        sourceUrl
                        webpSrcSet
                        webpSourceUrl
                    }
                }
                yandexMetrikaList {
                    name
                }
            }
            faqCommon {
                descr
                list {
                    defaultOpen
                    title
                    descr
                }
                title
            }
            includedServies {
                title
                includedServiesList {
                    title
                    descr
                }
            }
            rewiewCommon {
                listImg {
                    img {
                        node {
                            id
                            sourceUrl
                            webpSrcSet
                            webpSourceUrl
                        }
                    }
                }
                listVideo {
                    videoElem
                    cover {
                        node {
                            sourceUrl
                            webpSrcSet
                            webpSourceUrl
                        }
                    }
                }
                type
                fieldGroupName
            }
            sertificateCommon {
                listImg {
                    img {
                        node {
                            id
                            sourceUrl
                            webpSrcSet
                            webpSourceUrl
                        }
                    }
                }
                fieldGroupName
            }
            textOpenCommon {
                title
                descr
            }
            formModalCommon {
                id
                hash
                title
                descr
                nameBtn
                successMessage
                cf7FormDynamicFields
                yandexMetrikaList {
                    name
                }
            }
            mapCommon {
                centerX
                centerY
                zoom
                metka {
                    centerX
                    centerY
                    title
                    descr
                    color
                }
            }
        }
    }
}
