query getSeoPost($ID: ID!) {
    post(idType: SLUG, id: $ID) {
        seo {
            title
            metaDesc
            canonical
            breadcrumbs {
                url
                text
            }
            metaRobotsNoindex
            metaRobotsNofollow
            metaKeywords
        }
    }
}
